### PR TITLE
Add support for encoding_rs

### PR DESCRIPTION
**Pull request by nox**
This change is [Reviewable](https://reviewable.io/reviews/servo/tendril/37)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Nice! When I considered doing something like this previously it didn’t occur to me we could have (up to) three variants in the `LossyDecoderInner` enum.

r+ with CI fix (Travis is red)

**Comment by nox** [comment]
Seems like Homu sat on its hands.

@bors-servo retry force

**Pull request merged**
