### PR TITLE
Add FromIterator and Extend implementations

### PR DESCRIPTION
**Pull request by chris-morgan**
`FromIterator<T>` and `Extend<T>` are implemented for the following values of `T`:

- `char` for `StrTendril`;
- `u8` for `ByteTendril`;
- `&u8` for `ByteTendril`, for reasons of ergonomics (see also https://github.com/rust-lang/rfcs/pull/839 for justification);
- `&str` for `StrTendril`;
- `&[u8]` for `ByteTendril`;
- `&Tendril<F>` for `Tendril<F>` (the `Extend` implementation already existed; the `FromIterator` is added).

[Review on Reviewable](https://reviewable.io/reviews/servo/tendril/15)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Please use `&[b]` or `&[*b]` instead of `ref_slice`, like in #14. Other than this, looks good. (The third impl is in the spirit of https://github.com/rust-lang/rfcs/pull/839.)

While you’re at it, you may want to also implement `Extend` and rewrite `FromIterator` in terms of it. (But it’e fine as is.)

**Comment by chris-morgan** [comment]
OK, updated to address feedback, including adding `Extend` implementations. Funny how I forgot about that—I had looked at the `Extend<&Tendril<F>>` implementation, noted its irrelevance to the task at hand and forgotten to ever come back to it.

It might be good to implement `Extend<&str>` for `StrTendril` and `Extend<&[u8]>` for `ByteTendril`, ideally through `SliceFormat` though we can’t at present do it thus generically, as well. What say you?

**Comment by SimonSapin** [comment]
`std` has `impl<'a> Extend<&'a str> for String`, so adding it for `StrTendril` sounds fine. It doesn’t have the bytes or slice equivalent, but I don’t know a reason not to. So go for it if the coherence rules let you.

**Comment by chris-morgan** [comment]
I have rebased, updated and rendered everything consistent. Ready for merging, I believe.

**Comment by SimonSapin** [comment]
Looks great. Thanks!

**Pull request merged**
